name: Build SpargeAttn Wheels (Windows)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install-deps:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9']
        cuda-version: ['12.1.1']
      fail-fast: false
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    # 1. Явно указываем версию Visual Studio 2022
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
        export-path-to-vcvarsall: true
        export-path-to-vs: true
        
    - name: Verify cl.exe
      #shell: pwsh
      run: CL.EXE /v
