name: Build SpargeAttn Wheels (Windows)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install-deps:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9']
        cuda-version: ['12.1.1']
      fail-fast: false
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    # 1. Явно указываем версию Visual Studio 2022
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
        export-path-to-vcvarsall: true
        export-path-to-vs: true
        
    - name: Install CUDA ${{ matrix.cuda-version }}
      id: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        cuda: ${{ matrix.cuda-version }}
        sub-packages: '["nvcc", "cudart", "cublas", "curand"]'
        method: network
        
        
    - name: Add CUDA to PATH
      shell: pwsh
      run: |
        $cudaVersion = "${{ matrix.cuda-version }}"
        $cudaMajorMinor = $cudaVersion -replace '(\d+\.\d+)\..*', '$1'
        $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v$cudaMajorMinor"
        echo "CUDA_PATH=$cudaPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "PATH=$cudaPath\bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
    
    - name: Verify CUDA installation
      shell: pwsh
      run: nvcc --version
