name: Build SpargeAttn Wheels

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.12']
        cuda-version: ['12.3.0']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CUDA ${{ matrix.cuda-version }}
      if: matrix.os == 'windows-latest'
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        cuda: ${{ matrix.cuda-version }}
